### PR TITLE
Fix for #369

### PR DESCRIPTION
**Pull request by benjaoming**
Small optimization for the way that the TreeManager is found and add some extra tests

### CODE REVIEW

**Comment by benjaoming** [comment]
Not sure why the doctests are only failing on some django versions? I've added a fix to a problem that ideally would have made all tests fail :)

**Comment by benjaoming** [comment]
Sorry that this is getting confusing, just that I can't build all the environments locally, so having travis do the work is gr8 :+1:

**Comment by craigds** [comment]
np, I do that too, since I still haven't managed to get homebrew to compile *any* version of python 3 on my laptop :(

**Comment by benjaoming** [comment]
Okay after having uncommented the `_default_manager` part, it seems that the test that asserts this:

    self.assertTrue(isinstance(Person.objects.all()[0].get_children().none(), CustomTreeQueryset))

...which is a new test... is failing because of something different... I'll leave it out for this PR and then maybe we can find the separate cause of that?

Would that be okay?

**Comment by benjaoming** [comment]
I mean, it's only failing in Django 1.4 so it's kind of not the end of the world :)

**Comment by craigds** [comment]
I was under the impression that Django changed the behaviour of `.none()` recently? But I can't see that noted in [the docs](https://docs.djangoproject.com/en/1.8/ref/models/querysets/#django.db.models.query.QuerySet.none).

The docs say it should return an `EmptyQuerySet` so I don't really understand why you're asserting it's a `CustomTreeQueryset`.

**Comment by benjaoming** [comment]
Adding issue #371 for the django 1.4 test failure which has then just been removed from the tests for now until further decision is made.

**Comment by benjaoming** [comment]
Oh yes, you're right @craigds -- maybe we should create a test that asserts that it just has the custom methods of the custom queryset instead of looking at the type? Because AFAIK in Django 1.4, the approach would have been to create a `CustomEmptyQuerySet` as a separate type.

**Comment by benjaoming** [comment]
okay now we're at it, I'll just add the modification in here with the other things... so it's like:

1. Fix stuff in case someone was using `_default_manager`
1. Optimize stuff by not iterating everything to find a TreeManager on a Model, just look at `objects`
1. Create more tests for checking out custom stuff
1. Create a test for the .none() method
1. Alterate the test Manager to reflect the way that managers are written differently depending on Django 1.4/1.5 og Django 1.6+

**Comment by benjaoming** [comment]
Oh for crying out loud Travis, these tests work locally \*sigh\*

**Comment by benjaoming** [comment]
I can't seem to get the last part to work, namely to make Django 1.4 find custom methods on a customized EmptyQuerySet returned by a custom Manager's `get_empty_query_set()` method... hence the failures.

So well okay, maybe it's not that important? Let me just remove `_default_manager = objects` again to see if that's the cause although I really doubt it...

**Comment by craigds** [comment]
Yeah, I didn't think the empty queryset was guaranteed to have any custom methods on it. Maybe it does nowdays, but it doesn't surprise me that it doesn't in django 1.4.

It's probably fine to merge without that assert.

**Comment by craigds** [comment]
Probably a bit late for this, but you can run `tox` to run the tests in a bunch of different environments. Or `tox -e py27-14` specifically for django 1.4

**Comment by craigds** [comment]
Looks good. So this does what's required for django-wiki now? Do you mind squashing these into one commit? Cheers

**Comment by benjaoming** [comment]
@craigds yeah that's what I did but everything just passed here locally, also the `.none()` on Django 1.4.

**Comment by benjaoming** [comment]
Squashing and making new PR...

**Pull request closed without merging**
