### PR TITLE
Multiple databases configuration support

### PR DESCRIPTION
**Pull request by TheDeadOne**
Fix for issue #132

### CODE REVIEW

**Comment by jamalex** [comment]
Thanks so much for fixing this! We were facing the same issues.

@craigds Just wondering if you know when this is going to be included in a 0.8.5 release, so we can depend on the PyPI version in [Kolibri](https://github.com/learningequality/kolibri). Thanks!!

**Comment by TheDeadOne** [comment]
@jamalex my pleasure :)

**Comment by craigds** [comment]
@jamalex: 0.8.5 is now tagged and on PyPI 😄

**Comment by jamalex** [comment]
Awesome, thanks so much!

**Pull request merged**
