### PR TITLE
Bumped Django version. Fixed old pip issue.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by felixxm** [comment]
`pip>=8.0` doesn't support `python==3.2`. IMO we can drop python 3.2 support (see [[1]](https://docs.djangoproject.com/en/1.10/releases/1.8/#python-compatibility)).

**Comment by craigds** [comment]
yes, can drop python 3.2 support. Honestly I don't think anyone has used python 3.2 for ages :)

**Comment by craigds** [comment]
what's the old pip issue this fixes? Is that the bug causing travis to not find django 1.11a1 _sometimes_ ?

**Comment by felixxm** [comment]
Yes, I think that `pip` upgrade should help.

**Comment by craigds** [comment]
https://github.com/pypa/pip/issues/3511 suggests that pip 8 handles alpha versions _differently_ ¯\_(ツ)_/¯

I don't understand why the tests were passing _sometimes_. Do you know?

**Comment by felixxm** [comment]
It's a mystery for me. I thought that it is a old<7 pip issue, but it's hard do say.

**Pull request merged**
