### PR TITLE
Update doc links

### PR DESCRIPTION
**Pull request by tony**
Update docs to point to readthedocs.io

### CODE REVIEW

**Comment by matthiask** [comment]
Thanks! I'm not sure about the change from github to readthedocs for the documentation -- I'll leave the final decision to @craigds.

**Comment by craigds** [comment]
I never set up RTD. It looks like that RTD project is owned by @jbochi.

Since we'd need to potentially change the RTD config etc in future, I'd prefer not to change these unless we can get access to that.

@jbochi, how would you feel about surrendering the RTD project?

**Comment by craigds** [comment]
i should note: gh-pages is a bit of a pain, so RTD would be better :)

**Comment by tony** [comment]
I am not sure if gh-pages is updated by default, rtd is.

**Comment by matthiask** [comment]
@craigds @jbochi Surrendering the project completely isn't necessary. You could also add additional maintainers to the project (https://readthedocs.org/profiles/craigds/ and https://readthedocs.org/profiles/mk/ would be nice)

**Comment by tony** [comment]
Still think we should update to ReadTheDocs. It's automatically done on post-hook and other python docs have a home there

**Comment by jbochi** [comment]
Sorry for the late reply. I've added @craigds and mk as maintainers. Should I add someone else?  I don't mind deleting the project if you want to recreate it too.

**Pull request merged**
