### PR TITLE
Support dark django admin theme

### PR DESCRIPTION
**Pull request by tfeldmann**
Before:

Bildschirmfoto 2021-08-27 um 12 16 48

After:

Bildschirmfoto 2021-08-27 um 12 16 36

### CODE REVIEW

**Comment by OliverSieberling** [comment]
Hey there, when using firefox, the dark theme is used even thought firefox isn't in dark mode.SCS
image

**Comment by tfeldmann** [comment]
That's strange! Which OS  / FF version are you on?

**Comment by matthiask** [comment]
Hmm. @OliverSieberling Maybe you're not on Django 3.2? Older Django versions do not support a dark mode yet (I think). This also means that this change introduced a minimum Django version of 3.2 for the draggable MPTT admin for anyone using dark mode.

**Comment by lukasboehm97** [comment]
Hey all, I've got the same issue. using Django 3.2.7 and FF 91.0.2 . It works great with Crome however.

**Comment by tfeldmann** [comment]
I submitted a PR which should fix this problem. Please test 👍 #799

**Pull request merged**
