### PR TITLE
Django 1.9 compatibility

### PR DESCRIPTION
**Pull request by gavinwahl**
EMPTY_CHANGELIST_VALUE was removed and replaced with get_empty_value_display.

### CODE REVIEW

**Comment by craigds** [comment]
wow, django versions are crazy. I've barely got to grips with 1.8 being released :/

**Comment by gavinwahl** [comment]
Any status update on this?

**Comment by craigds** [comment]
sorry, thanks, merged :)

**Comment by Wtower** [comment]
Relevant issue #391 

For the sake of searchability, the rendered error message is:

> Invalid template library specified. ImportError raised when trying to load `mptt.templatetags.mptt_admin`: cannot import name `EMPTY_CHANGELIST_VALUE`

**Comment by Wtower** [comment]
Hey craigds, nice job mate. Any plans on a new release+pip version out of curiosity?

**Comment by un1t** [comment]
Hi! Pease upload this fix to pypi.

**Comment by ninjaa** [comment]
yes, please upload this fix to pypi

**Comment by matthiask** [comment]
There might still be a new bug around blocking the next release. Help would be very much appreciated here: https://github.com/django-mptt/django-mptt/issues/424

Thanks in advance!

**Pull request merged**
