### PR TITLE
Fix dismissRelatedLookupPopup issue with Django 1.9 and below

### PR DESCRIPTION
**Pull request by yakky**
This is a preliminary fix for #536 
Tested to work on Django 1.8, 1.9 and 1.10

### CODE REVIEW

**Comment by yakky** [comment]
@craigds could you check if it's an acceptable fix for the issue? If so, I'll check the tests and I will make this mergeable

**Comment by craigds** [comment]
Thanks! Since you asked, I'd prefer a simple version check than the feature-checking check. Something like:

```python
if django.VERSION < (1, 10):
    opener = ...
```

**Comment by yakky** [comment]
@craigds will comply and I will bring this in shape for merge. thanks for answering!

**Comment by yakky** [comment]
@craigds fixed, thanks for the review

**Comment by yakky** [comment]
Thanks!

**Pull request merged**
