### PR TITLE
Fix TreeManager._move_child_within_tree breaks with UUIDField() as primary key.

### PR DESCRIPTION
**Pull request by xyb**
Thanks for #357 and #322.

### CODE REVIEW

**Comment by craigds** [comment]
Thanks. I've never used UUIDField myself, is the implication that `obj.pk` doesn't work for UUIDField for some reason? Do you know why that would be?

**Comment by craigds** [comment]
I should read the linked things before replying. #357 describes the issue pretty well. It's interesting that django's UUIDField returns an object which doesn't adapt in psycopg2 😞

**Comment by craigds** [comment]
Thanks for the patch and tests :)

I'm pondering where we should go with this. IMHO this is a less-than-ideal solution since it scatters the fix in several places in the codebase. It does work though :)

One alternative would be to rewrite the custom-SQL queries in django-mptt using the ORM. That wasn't possible back in the early days, but now we're supporting django 1.8+ we should be able to do it. Django 1.8 adds [Case/When](https://docs.djangoproject.com/en/1.9/ref/models/conditional-expressions/#conditional-expressions), more powerful F expressions, etc.

It looks like the methods that would need modifications are:

* `TreeManager._inter_tree_move_and_close_gap`
* `TreeManager._move_child_within_tree`
* `TreeManager._move_root_node`

It might make the huge queries even less readable, but it would solve this problem. I'm assuming of course that the ORM will be able to adapt its own UUID objects before passing them to the database backend. (Probably worth checking that before rewriting those huge SQL queries)

I'm leaning toward that solution since avoiding custom SQL will make the code more robust in general. Thoughts?

**Comment by craigds** [comment]
Also see #466 which is an unrelated issue with the same query

**Comment by xyb** [comment]
@craigds I agree with refactoring to using Django's ORM will be great for future developments, it's hard to accomplish all Django ORM's benefits with hand made SQL queries. But it should be done separately from this bug-fix. I have interest in the refactoring but do not have enough time recently.

**Comment by matthiask** [comment]
@craigds I think we should merge this since this pull request simply makes django-mptt's code consistent. The improvement might still happen, but this pull request works and solves real problems right now.

**Comment by michaeljohnbarr** [comment]
@xyb Great work! Thanks for taking this and running with it. @matthiask thanks for the merge!

**Comment by matthiask** [comment]
Thanks @michaeljohnbarr , but you have to thank @craigds for the merge :)

**Pull request merged**
