### PR TITLE
Mark this project as unmaintained

### PR DESCRIPTION
**Pull request by matthiask**
See https://twitter.com/matthispam/status/1367205308439949313 and all the reports about missing release notes etc.

### CODE REVIEW

**Comment by claudep** [comment]
I think suggesting replacement packages should be very nice!

**Comment by matthiask** [comment]
> I think suggesting replacement packages should be very nice!

Thanks, that's an excellent suggestion!

**Comment by claudep** [comment]
Awesome, thanks! And many thanks also for all the energy you put in this package until now. It is appreciated!!

**Review by craigds — APPROVED** [review]
Great call. I think the alternative projects do a better job these days anyway. I came to the realisation at some point that MPTT can't really be managed correctly in the app layer, doing it in the db or just using CTEs seems like the way to go.

Thanks so much for putting in all the work to maintain this project. Hope 2021 improves for you

**Review by goodtune — APPROVED** [review]

**Pull request merged**
